# Generated by Django 3.0.5 on 2020-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('desc', models.TextField(max_length=1000)),
                ('launchDate', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
